import React from 'react'

const Database = () => {
    const pokemons = [
        {name: "pikachu",
        id:25,
        type:"electric",
        weight:6,
        height:0.4 ,
        primaryMove: "mega-punch",
        secondaryMove: "pay-day",
        description:"Pikachu that can generate powerfull electricity have check sacs that are extra soft and super stretchy",
        hp:35,
        atk:55,
        def:40,
        satk:50,
        sdef:50,
        spd:90,
        },
        {name: "squirtle",
        id:7,
        type:"water",
        weight:9,
        height:0.5 ,
        primaryMove: "torrent",
        secondaryMove: "rain-Dish",
        description:"when it retracts its long neck into it shell, it squirts out water with vigorous force.",
        hp:44,
        atk:48,
        def:65,
        satk:50,
        sdef:64,
        spd:43,
        },
        {name: "Butterfly",
        id:12,
        type:"bag",
        secondType:"flying",
        weight:32,
        height:1.1 ,
        primaryMove: "compound-eyes",
        secondaryMove: "tinted-lents",
        description:"in battle, it flaps it wings and great speed to release hiughlit toxic dust into the air",
        hp:60,
        atk:45,
        def:50,
        satk:90,
        sdef:80,
        spd:70,
        },
        {name: "charmander",
        id:54,
        type:"fire",
        weight:8.5,
        height:0.6 ,
        primaryMove: "mega-punch",
        secondaryMove: "fire-punch",
        description:"it has a preference for hot things. when it rains, steam is save to spot from the tip of its tail.",
        hp:39,
        atk:52,
        def:43,
        satk:60,
        sdef:50,
        spd:65,
        },
        {name: "bulbasaur",
        id:1,
        type:"grass",
        secondarytype:"poison",
        weight:6.9,
        height:0.7 ,
        primaryMove: "chlorophill",
        secondaryMove: "overgrow",
        description:"the its a plant sid on his back, right from the day this pokemon grow. the sid slowly drows larger.",
        hp:45,
        atk:49,
        def:49,
        satk:65,
        sdef:65,
        spd:45,
        },
        {name: "ghastly",
        id:92,
        type:"ghost",
        secondarytype:"type",
        weight:0.1,
        height:1.3 ,
        primaryMove: "levitate",
        description:"born from gases, anyone got faint if engulfed by its gaseous body, which contains poison.",
        hp:30,
        atk:35,
        def:30,
        satk:100,
        sdef:35,
        spd:80,
        },
        {name: "ditto",
        id:132,
        type:"normal",
        weight:4,
        height:0.3 ,
        primaryMove: "limber",
        secondaryMove: "imposter",
        description:"it can reconstitute its entire celular estructure, to change into what it sees, but it returns to normal when it relaxes.",
        hp:48,
        atk:48,
        def:48,
        satk:48,
        sdef:48,
        spd:48,
        },
        {name: "mew",
        id:152,
        type:"psychic",
        weight:4,
        height:0.4 ,
        primaryMove: "sinchronize",
        description:"when ed trhu a microscope, this pokemon's, short find, delicates ears can be seen.",
        hp:100,
        atk:100,
        def:100,
        satk:100,
        sdef:100,
        spd:100,
        },
        {name: "aron",
        id:304,
        type:"still",
        secondaryMove:"rock",
        weight:60,
        height:0.4 ,
        primaryMove: "sturdy",
        secondaryMove: "rock-head",
        description:"it its iron ore - and sometimes railroad trucks - to build up the still armor that protects its body.",
        hp:50,
        atk:70,
        def:100,
        satk:40,
        sdef:40,
        spd:30,
        }
    ]
  
  
    return (

    <div>


    </div>
  )
}

export default Database