const Database = [
  {
    name: "Pikachu",
    id: 25,
    type: "Electric",
    color: "#F9CF30",
    weight: 6,
    height: 0.4,
    primaryMove: "Mega-punch",
    secondaryMove: "pay-day",
    description:
      "Pikachu that can generate powerfull electricity have check sacs that are extra soft and super stretchy",
    hp: 35,
    atk: 55,
    def: 40,
    satk: 50,
    sdef: 50,
    spd: 90,
  },
  {
    name: "Squirtle",
    id: 7,
    type: "Water",
    color: "#6493EB",
    weight: 9,
    height: 0.5,
    primaryMove: "Torrent",
    secondaryMove: "Rain-Dish",
    description:
      "when it retracts its long neck into its shell, it squirts out water with vigorous force.",
    hp: 44,
    atk: 48,
    def: 65,
    satk: 50,
    sdef: 64,
    spd: 43,
  },
  {
    name: "Butterfree",
    id: 12,
    type: "Bug",
    color: "#A7B723",
    secondaryType: "Flying",
    weight: 32,
    height: 1.1,
    primaryMove: "Compound-eyes",
    secondaryMove: "Tinted-lents",
    description:
      "in battle, it flaps its wings at great speed to release highly toxic dust into the air",
    hp: 60,
    atk: 45,
    def: 50,
    satk: 90,
    sdef: 80,
    spd: 70,
  },
  {
    name: "Charmander",
    id: 54,
    type: "Fire",
    color: "#F57D31",
    weight: 8.5,
    height: 0.6,
    primaryMove: "Mega-punch",
    secondaryMove: "Fire-punch",
    description:
      "it has a preference for hot things. when it rains, steam is said to spout from the tip of its tail.",
    hp: 39,
    atk: 52,
    def: 43,
    satk: 60,
    sdef: 50,
    spd: 65,
  },
  {
    name: "Bulbasaur",
    id: 1,
    type: "Grass",
    color: "#74CB48",
    secondaryType: "Poison",
    weight: 6.9,
    height: 0.7,
    primaryMove: "Chlorophill",
    secondaryMove: "Overgrow",
    description:
      "the its a plant sid on his back, right from the day this pokemon grow. the sid slowly drows larger.",
    hp: 45,
    atk: 49,
    def: 49,
    satk: 65,
    sdef: 65,
    spd: 45,
  },
  {
    name: "Ghastly",
    id: 92,
    type: "Ghost",
    color: "#70559B",
    secondaryType: "Type",
    weight: 0.1,
    height: 1.3,
    primaryMove: "Levitate",
    description:
      "born from gases, anyone would faint if engulfed by its gaseous body, which contains poison.",
    hp: 30,
    atk: 35,
    def: 30,
    satk: 100,
    sdef: 35,
    spd: 80,
  },
  {
    name: "Ditto",
    id: 132,
    type: "Normal",
    color: "#AAA67F",
    weight: 4,
    height: 0.3,
    primaryMove: "Limber",
    secondaryMove: "Imposter",
    description:
      "it can reconstitute its entire celular estructure, to change into what it sees, but it returns to normal when it relaxes.",
    hp: 48,
    atk: 48,
    def: 48,
    satk: 48,
    sdef: 48,
    spd: 48,
  },
  {
    name: "Mew",
    id: 152,
    type: "Psychic",
    color: "#FB5584",
    weight: 4,
    height: 0.4,
    primaryMove: "Sinchronize",
    description:
      "when viewed trhought a microscope, this pokemon's short, fine, delicate hair can be seen.",
    hp: 100,
    atk: 100,
    def: 100,
    satk: 100,
    sdef: 100,
    spd: 100,
  },
  {
    name: "Aron",
    id: 304,
    type: "Steel",
    secondaryType: "Rock",
    color: "#B7B9D0",
    weight: 60,
    height: 0.4,
    primaryMove: "Sturdy",
    secondaryMove: "Rock-head",
    description:
      "it eats iron ore - and sometimes railroad trucks - to build up the steel armor that protects its body.",
    hp: 50,
    atk: 70,
    def: 100,
    satk: 40,
    sdef: 40,
    spd: 30,
  },
];

export default Database;
