const Database = [
  {
    name: "pikachu",
    id: 25,
    type: "electric",
    color: "yellow",
    weight: 6,
    height: 0.4,
    primaryMove: "mega-punch",
    secondaryMove: "pay-day",
    description:
      "Pikachu that can generate powerfull electricity have check sacs that are extra soft and super stretchy",
    hp: 35,
    atk: 55,
    def: 40,
    satk: 50,
    sdef: 50,
    spd: 90,
  },
  {
    name: "squirtle",
    id: 7,
    type: "water",
    color: "skyblue",
    weight: 9,
    height: 0.5,
    primaryMove: "torrent",
    secondaryMove: "rain-Dish",
    description:
      "when it retracts its long neck into its shell, it squirts out water with vigorous force.",
    hp: 44,
    atk: 48,
    def: 65,
    satk: 50,
    sdef: 64,
    spd: 43,
  },
  {
    name: "Butterfree",
    id: 12,
    type: "bug",
    color: "light-green",
    secondType: "flying",
    weight: 32,
    height: 1.1,
    primaryMove: "compound-eyes",
    secondaryMove: "tinted-lents",
    description:
      "in battle, it flaps its wings at great speed to release highly toxic dust into the air",
    hp: 60,
    atk: 45,
    def: 50,
    satk: 90,
    sdef: 80,
    spd: 70,
  },
  {
    name: "charmander",
    id: 54,
    type: "fire",
    color: "orange",
    weight: 8.5,
    height: 0.6,
    primaryMove: "mega-punch",
    secondaryMove: "fire-punch",
    description:
      "it has a preference for hot things. when it rains, steam is said to spout from the tip of its tail.",
    hp: 39,
    atk: 52,
    def: 43,
    satk: 60,
    sdef: 50,
    spd: 65,
  },
  {
    name: "bulbasaur",
    id: 1,
    type: "grass",
    color: "green",
    secondarytype: "poison",
    weight: 6.9,
    height: 0.7,
    primaryMove: "chlorophill",
    secondaryMove: "overgrow",
    description:
      "the its a plant sid on his back, right from the day this pokemon grow. the sid slowly drows larger.",
    hp: 45,
    atk: 49,
    def: 49,
    satk: 65,
    sdef: 65,
    spd: 45,
  },
  {
    name: "ghastly",
    id: 92,
    type: "ghost",
    color: "violet",
    secondarytype: "type",
    weight: 0.1,
    height: 1.3,
    primaryMove: "levitate",
    description:
      "born from gases, anyone would faint if engulfed by its gaseous body, which contains poison.",
    hp: 30,
    atk: 35,
    def: 30,
    satk: 100,
    sdef: 35,
    spd: 80,
  },
  {
    name: "ditto",
    id: 132,
    type: "normal",
    color: "grey",
    weight: 4,
    height: 0.3,
    primaryMove: "limber",
    secondaryMove: "imposter",
    description:
      "it can reconstitute its entire celular estructure, to change into what it sees, but it returns to normal when it relaxes.",
    hp: 48,
    atk: 48,
    def: 48,
    satk: 48,
    sdef: 48,
    spd: 48,
  },
  {
    name: "mew",
    id: 152,
    type: "psychic",
    color: "pink",
    weight: 4,
    height: 0.4,
    primaryMove: "sinchronize",
    description:
      "when viewed trhought a microscope, this pokemon's short, fine, delicate hair can be seen.",
    hp: 100,
    atk: 100,
    def: 100,
    satk: 100,
    sdef: 100,
    spd: 100,
  },
  {
    name: "aron",
    id: 304,
    type: "steel",
    secondaryType: "rock",
    color: "light-violet",
    weight: 60,
    height: 0.4,
    primaryMove: "sturdy",
    secondaryMove: "rock-head",
    description:
      "it eats iron ore - and sometimes railroad trucks - to build up the steel armor that protects its body.",
    hp: 50,
    atk: 70,
    def: 100,
    satk: 40,
    sdef: 40,
    spd: 30,
  },
];

export default Database;
